### PR TITLE
Remove unused and uncessesary init.pp

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by ferventcoder** [comment]
I forget, did you add this at one poitn?

**Comment by ferventcoder** [comment]
Before we go removing this, let's make sure all of the documentation in it is represented in the readme.

**Comment by hunner** [comment]
Nothing in the readme about the class.

**Comment by cyberious** [comment]
@ferventcoder this came about b/c Docs are updating the Readme to represent the current state of this module

**Comment by ferventcoder** [comment]
@hunner @cyberious I meant the documentation IN the init.pp - making sure it is represented elsewhere, like in the Readme.

**Comment by ferventcoder** [comment]
@hunner specifically https://github.com/puppetlabs/puppetlabs-reboot/blob/f5d37f0546d2232d78880091b1eab967a93e1f04/manifests/init.pp#L3-L108

**Comment by Iristyle** [comment]
@ferventcoder is correct @hunner ... the README for the module no longer has the details for parameters / properties like this sample manifest that was removed did.  

https://github.com/puppetlabs/puppetlabs-reboot/blob/f5d37f0546d2232d78880091b1eab967a93e1f04/manifests/init.pp#L17-L57

The rest of the content was already in the `README`, but the above should probably be added.

**Comment by Iristyle** [comment]
ping @cyberious / @hunner to add the above lines back to the `README`

**Pull request merged**
