### PR TITLE
Fix reboot message for linux hosts

### PR DESCRIPTION
**Pull request by nmaludy**
Previously Linux hosts that were rebooted with a warning message didn't have their message displayed unless the reboot delay was >= 60 seconds.

Looks like this is a race condition with the way `shutdown -r +0 "my message"` works because that doesn't work on the CLI either when i tried it.

On the CLI manually i was able to get the message to display by doing: `wall "my message"; shutdown -r +0`.

To fix this problem i checked to see if we're waiting for < 1 minute (ie. using the `sleep` command to wait) and if so run a `wall "$message"` before executing the shutdown. This way the message will be displayed.

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thanks for submitting the PR @nmaludy .

**Comment by nmaludy** [comment]
@sheenaajay i resolved the merge conflict in the CHANGELOG, should be good to go now.

**Comment by sheenaajay** [comment]
Screen Shot 2019-08-14 at 13 16 23

**Comment by sheenaajay** [comment]
Thank you @nmaludy

**Pull request merged**
