### PR TITLE
Cleanup: Changed to ctrl::sleep() and removed redundant reboot::sleep() function

### PR DESCRIPTION
**Pull request by fetzerms**
Bolt comes with a built-in sleep function (since at least two years, according to git). The reboot::sleep() function seems to be redundant. It does not do anything more or special than the built-in one. Hence: I think we can remove it and use the built-in method for better maintainability.

I did not (yet?) create a MODULES-Issue for it, as it is just a minor code quality improvement and not really an issue or a feature to be requested. If a Jira-issue needs to be created, I can still do it tho.

### CODE REVIEW

**Comment by pmcmaw** [comment]
Thanks for this PR! Great spot! 
I would like to thank you for your time and effort on getting this over the line.
Merging.

**Comment by fetzerms** [comment]
Thank you very much for merging @pmcmaw . Is there a fixed schedule, when new releases will be published to puppet forge?

**Comment by fetzerms** [comment]
Thanks for the explanation. Great! I am happy to receive the latest fixes via forge soon :-)

**Comment by pmcmaw** [comment]
This module was released onto the Forge yesterday and includes your changes, thank you for your contributions to Puppet :-)

**Pull request merged**
